name: flutter_incall_manager_example
description: Demonstrates how to use the flutter_incall_manager plugin.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.5

  flutter_incall_manager:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.17.0 <3.0.0"